version: "3.7"
services:

  front-envoy:
    build:
      context: gateway
      dockerfile: ./Dockerfile
    networks:
      - envoymesh
    volumes:
      - ./gateway/front-envoy.yaml:/etc/front-envoy.yaml
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  ext_authz-grpc-service:
    build:
      context: authz
      dockerfile: ./Dockerfile
    volumes:
      - ./authz/users.json:/etc/users.json
    links:
      - kratos
    depends_on:
      - kratos
    networks:
      envoymesh:
        aliases:
          - ext_authz-grpc-service

  upstream-service:
    build:
      context: cowboy
      dockerfile: ./Dockerfile
    volumes:
      - /Users/evalsocket/.kube/config:/etc/config.yaml
      - ./cowboy/config.json:/config.json
    environment:
      - SERVE_HTTP=true
      - ES_URL=http://elasticsearch:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      envoymesh:
        aliases:
          - upstream-service

  kratos-migrate:
    image: oryd/kratos:latest-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./config
        target: /etc/config/kratos
    command:
      -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - envoymesh

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:latest
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - PORT=4455
      - SECURITY_MODE=session
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433
    links:
      - kratos
    depends_on:
      - kratos
    expose:
      - "4455"
    ports:
      - "4455:4455"
    networks:
      envoymesh:
        aliases:
          - kratos-selfservice-ui-node

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest-sqlite
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command:
      serve -c /etc/config/kratos/kratos.yml --dev
    volumes:
      -
        type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      -
        type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      envoymesh:
        aliases:
          - kratos-service

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - envoymesh

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - envoymesh

networks:
  envoymesh: {}

volumes:
  kratos-sqlite: